FROM eclipse-temurin:17-jdk-focal
COPY target/frontend-communication-service-0.0.1-SNAPSHOT.jar frontend-communication-service-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/frontend-communication-service-0.0.1-SNAPSHOT.jar"]